version: "3.3"
services:
  spark-master:
    image: vitotsg/cluster-apache-spark:3.1.2
    ports:
      - "19090:8080"
      - "17077:7077"
      - "15432:5432"
    volumes:
      - /home/ics/workspace:/workspace-1
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: vitotsg/cluster-apache-spark:3.1.2
    ports:
      - "19091:8080"
      - "17000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - /home/ics/workspace:/workspace-1
  spark-worker-b:
    image: vitotsg/cluster-apache-spark:3.1.2
    ports:
      - "19092:8080"
      - "17001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - /home/ics/workspace:/workspace-1